### ISSUE TITLE
SFCC-CI deployment Error

### ISSUE THREAD

**Issue by mayankshukla10** [SalesforceCommerceCloud/sfcc-ci#142]
Hi,

One of the customers is facing an issue while trying to deploy the code to staging using SFCC-CI with 2FA. But they are getting below error:
Error: Network or certificate error
Error: An error occured. Try running the command again with -D,--debug flag.
[DEBUG] Error code: EPROTO, message: write EPROTO 4447045056:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1498:SSL alert number 40
4447045056:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
, stack: Error: write EPROTO 4447045056:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1498:SSL alert number 40
4447045056:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

We have checked that their certificate is still valid till 2027. Could anyone point why this may be coming.

**Comment by tobiaslohr** [comment]
Hi @mayankshukla10, 
is the cert (and passphrase) working if using another client to deploy code to staging?

**Comment by HeidiRechek** [comment]
I have this issue also. I was able to upload code to our 2FA environment by running manual commands from the Jenkins slave server. When I add certificate to jenkins and attempt automation, I get: 
sfcc-ci code:deploy -D version2.zip -i cert.staging.web.****.demandware.net -c **** -p ****

[DEBUG] No dw.json found in d:\jenkins\workspace\Test_jobs\Deploy_to_PODs

REQUEST {

  baseUrl: 'https://cert.staging.web.****.demandware.net',

  uri: '/on/demandware.servlet/webdav/Sites/cartridges/version2.zip',

  auth: { bearer: 'r0lZyc1pCCiW-fcceA1wROXV-Ng' },

  strictSSL: true,

  method: 'PUT',

  callback: [Function]

}

REQUEST make request https://cert.staging.web.****.demandware.net/on/demandware.servlet/webdav/Sites/cartridges/version2.zip

{

  request: {

    debugId: 1,

    uri: 'https://cert.staging.web.****.demandware.net/on/demandware.servlet/webdav/Sites/cartridges/version2.zip',

    method: 'PUT',

    headers: {

      host: 'cert.staging.web.****.demandware.net',

      authorization: 'Bearer r0lZyc1pCCiW-fcceA1wROXV-Ng',

      'content-type': 'application/zip'

    }

  }

}

Error: Network or certificate error

Error: An error occured. Try running the command again with -D,--debug flag.

[DEBUG] Error code: EPROTO, message: write EPROTO 12500:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40

, stack: Error: write EPROTO 12500:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40



    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)

script returned exit code 1

**Comment by aseth8** [comment]
> I have this issue also. I was able to upload code to our 2FA environment by running manual commands from the Jenkins slave server. When I add certificate to jenkins and attempt automation, I get:
> sfcc-ci code:deploy -D version2.zip -i cert.staging.web.****.demandware.net -c **** -p ****
> 
> [DEBUG] No dw.json found in d:\jenkins\workspace\Test_jobs\Deploy_to_PODs
> 
> REQUEST {
> 
> baseUrl: 'https://cert.staging.web.****.demandware.net',
> 
> uri: '/on/demandware.servlet/webdav/Sites/cartridges/version2.zip',
> 
> auth: { bearer: 'r0lZyc1pCCiW-fcceA1wROXV-Ng' },
> 
> strictSSL: true,
> 
> method: 'PUT',
> 
> callback: [Function]
> 
> }
> 
> REQUEST make request https://cert.staging.web.****.demandware.net/on/demandware.servlet/webdav/Sites/cartridges/version2.zip
> 
> {
> 
> request: {
> 
> ```
> debugId: 1,
> 
> uri: 'https://cert.staging.web.****.demandware.net/on/demandware.servlet/webdav/Sites/cartridges/version2.zip',
> 
> method: 'PUT',
> 
> headers: {
> 
>   host: 'cert.staging.web.****.demandware.net',
> 
>   authorization: 'Bearer r0lZyc1pCCiW-fcceA1wROXV-Ng',
> 
>   'content-type': 'application/zip'
> 
> }
> ```
> 
> }
> 
> }
> 
> Error: Network or certificate error
> 
> Error: An error occured. Try running the command again with -D,--debug flag.
> 
> [DEBUG] Error code: EPROTO, message: write EPROTO 12500:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40
> 
> , stack: Error: write EPROTO 12500:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40
> 
> ```
> at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
> ```
> 
> script returned exit code 1

how did you resolve this error?

**Comment by jiahuichen93** [comment]
could you please share how did you resolve this error?

**Comment by tobiaslohr** [comment]
@jiahuichen93 In most of the case a re-generation of the client cert has solved this problem. Please make sure, you are using the right cert bundle for the client cert generation. If you are unsure, you can always request the current cert bundle by opening a Salesforce Support Case.

**Comment by LeelaOtterbox** [comment]
I'm also having the same error for code version activation but code upload works fine. I'm doing manual activation.
