### ISSUE TITLE
Javascript API: Code Version activation not triggering

### ISSUE THREAD

**Issue by dmersiowsky** [SalesforceCommerceCloud/sfcc-ci#161]
Code activation through the Javascript API does not seem to trigger while the callback doesn't get an error.

Calling this API:

```
let codeApi = require('sfcc-ci').code;
codeApi.activate(instance, version, token, function (error) { /*error is empty*/ });
```

**Comment by dmersiowsky** [comment]
Looks like sfcc-ci is throwing an error itself:

```
Error: null
    at XXXX/node_modules/sfcc-ci/lib/code.js:425:26
    at Object.ensureValidToken (XXXX/node_modules/sfcc-ci/lib/ocapi.js:94:9)
    at Request._callback (/Users/dmersiowsky/source/build-suite-dev/build/node_modules/sfcc-ci/lib/code.js:414:19)
    at Request.self.callback (XXXX/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (XXXX/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (XXXX/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
```

**Comment by tobiaslohr** [comment]
>while the callback doesn't get an error.

@dmersiowsky can you verify, if you are running into either https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/master/lib/code.js#L415 or https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/master/lib/code.js#L419 condition? In that case, the callback does not get an Error passed

**Comment by dmersiowsky** [comment]
Didn't debug through that yet but I can confirm that the code version is not yet active and it doesn't get activated either.

**Comment by dmersiowsky** [comment]
Looks like we're calling `new Error(null)` in https://github.com/SalesforceCommerceCloud/sfcc-ci/blob/master/lib/code.js#L425.

I'll investigate.

**Comment by C-Lacerda** [comment]
H @dmersiowsky  have you solved?
