### ISSUE TITLE
Error on sandbox:realm:list

### ISSUE THREAD

**Issue by Gektorian** [SalesforceCommerceCloud/sfcc-ci#168]
When I execute `sfcc-ci sandbox:realm:list` I'm getting the following error:
```
# sfcc-ci sandbox:realm:list
/home/sfcc/sfcc-ci/lib/sandbox.js:751
                if (list.length === 0) {
                         ^

TypeError: Cannot read property 'length' of undefined
    at /home/sfcc/sfcc-ci/lib/sandbox.js:751:26
    at /home/sfcc/sfcc-ci/lib/sandbox.js:228:13
    at ensureValidToken (/home/sfcc/sfcc-ci/lib/ocapi.js:94:9)
    at Request._callback (/home/sfcc/sfcc-ci/lib/ocapi.js:148:9)
    at Request.self.callback (/home/sfcc/sfcc-ci/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/home/sfcc/sfcc-ci/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (/home/sfcc/sfcc-ci/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:281:20)
```

**Comment by sftschaerff** [comment]
Hi @Gektorian,

I have the following questions regarding your error message:
- Do you see any other relevant message or error in your terminal?
- Are you properly authenticated?
- Is your Account Manager User assigned to any instance (you can check that in controlcenter)?

Best regards
Tobias

**Comment by Gektorian** [comment]
Hi Tobias,

The issue behind this error was that I did not have enough permissions defined in the control center. After I got more permissions in the account manager, issue was solved.

Should we extend login in the sfcc-ci and put try/catch with the error message to validate permissions in the control center?

**Comment by sftschaerff** [comment]
Hi @Gektorian,

I'm glad that the issue got solved.
I will take your idea with me and think about it.

Thank you for the input!

Best regards
Tobias
