### ISSUE TITLE
Development Build Failure Error - code deploy: 521 - Origin Down!

### ISSUE THREAD

**Issue by mukul-kulshrestha** [SalesforceCommerceCloud/sfcc-ci#208]
Hi,

when deploying code via Jenkins (OCAPI used here for code upload and data), getting below error frequently on a development instance, can you please provide inputs on this?
Below is the brief log. Attached full log file

**code deploy: 521 - Origin Down!
hudson.AbortException: 521 - Origin Down!**
at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.OpenCommerceAPI.unzipCartridge(OpenCommerceAPI.java:927)
at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.DeployBuilder$DeployCallable.invoke(DeployBuilder.java:871)
at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.DeployBuilder$DeployCallable.invoke(DeployBuilder.java:442)
at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3122)
at hudson.remoting.UserRequest.perform(UserRequest.java:211)
at hudson.remoting.UserRequest.perform(UserRequest.java:54)
at hudson.remoting.Request$2.run(Request.java:375)
at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to build-agent-01
at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
at hudson.remoting.Channel.call(Channel.java:1001)
at hudson.FilePath.act(FilePath.java:1070)
at hudson.FilePath.act(FilePath.java:1059)
at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.DeployBuilder.perform(DeployBuilder.java:267)
at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 4 more

**Comment by ibrianli** [comment]
+1 , i am experiencing a similar issue, although it appears intermittent. we're getting error 521 response code when uploading data files.

**Comment by tobiaslohr** [comment]
@mukul-kulshrestha On which CLI command are you receiving this? I can see java files referenced. The CLI is implemented in Node, not Java. So is this question related to the CLI at all?

**Comment by tobiaslohr** [comment]
@mukul-kulshrestha is this issue still relevant or can we close it?

**Comment by tobiaslohr** [comment]
@mukul-kulshrestha Quick check-in: were you able to resolve the issue and can we close the ticket?
