### ISSUE TITLE
Module Colors not found

### ISSUE THREAD

**Issue by mgerrits-suit** [SalesforceCommerceCloud/sfcc-ci#225]
Hi,

Since version 2.7.0 I get an error:
```
❯ sfcc-ci
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'colors'
Require stack:
- C:\Users\xxxxx\AppData\Roaming\npm\node_modules\sfcc-ci\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\sfcc-ci\cli.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\sfcc-ci\\cli.js'
  ]
}
```
I was looking for this missing package in package.json and it is listed under dev-dependencies.

Regards,
Martijn

**Comment by tobiaslohr** [comment]
Hi @mgerrits-suit,

thanks for raising! How are you using/installing the tool? Do you use a binary or do you clone and npm install?

**Comment by mgerrits-suit** [comment]
@tobiaslohr, I'm installing with `npm install sfcc-ci -g`

**Comment by tobiaslohr** [comment]
ok and when are you getting the error? which command are you using after installing?

**Comment by mgerrits-suit** [comment]
I tried several command like `sfcc-ci auth:login` or just `sfcc-ci`. They all exit with the same error `Error: Cannot find module 'colors'`

**Comment by tobiaslohr** [comment]
@mgerrits-suit Can you check https://github.com/SalesforceCommerceCloud/sfcc-ci/pull/226 and see if that fixes the issue for you?

**Comment by SolidPatterns** [comment]
We are having the same issue. We have worked around it for now by changing our npm install command.

Old command:
`npm install -g sfcc-ci`
New command:
`npm install -g sfcc-ci@2.6.0`

Here are the logs with the error:
`2021-06-07T11:56:02.9193486Z > sfcc-ci client:auth "xxxx" "***"
2021-06-07T11:56:02.9193832Z 
2021-06-07T11:56:03.0119614Z internal/modules/cjs/loader.js:818
2021-06-07T11:56:03.0120268Z   throw err;
2021-06-07T11:56:03.0120920Z   ^
2021-06-07T11:56:03.0121068Z 
2021-06-07T11:56:03.0121432Z Error: Cannot find module 'colors'
2021-06-07T11:56:03.0121942Z Require stack:
2021-06-07T11:56:03.0123346Z - C:\npm\prefix\node_modules\sfcc-ci\cli.js
2021-06-07T11:56:03.0124430Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-06-07T11:56:03.0126565Z     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-06-07T11:56:03.0126965Z     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-06-07T11:56:03.0127473Z     at require (internal/modules/cjs/helpers.js:74:18)
2021-06-07T11:56:03.0128722Z     at Object.<anonymous> (C:\npm\prefix\node_modules\sfcc-ci\cli.js:8:14)
2021-06-07T11:56:03.0129354Z     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-06-07T11:56:03.0129879Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-06-07T11:56:03.0130245Z     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-06-07T11:56:03.0130635Z     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-06-07T11:56:03.0131031Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2021-06-07T11:56:03.0131365Z   code: 'MODULE_NOT_FOUND',
2021-06-07T11:56:03.0131714Z   requireStack: [ 'C:\\npm\\prefix\\node_modules\\sfcc-ci\\cli.js' ]
2021-06-07T11:56:03.0131999Z }`

**Comment by tobiaslohr** [comment]
We've built a new release (see https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/tag/v2.7.1), please validate.

**Comment by mgerrits-suit** [comment]
Checked and it works now.
