### ISSUE TITLE
Stage upload fails with sslv3 alert handshake failure

### ISSUE THREAD

**Issue by vruikar-desoto** [SalesforceCommerceCloud/sfcc-ci#327]
### sfcc-ci Version

2.8.0

### What happened?

We have been using sfcc-ci version 2.6.0 which was breaking because of res null check.
_/var/lib/jenkins/workspace/Staging Build v2/node_modules/sfcc-ci/lib/webdav.js:211
            if (res.statusCode >= 400) {
                    ^
TypeError: Cannot read property 'statusCode' of undefined_

To fix this we updated the sfcc-ci version to 2.8.0 and now build process is breaking at upload stage. Overall build status is successful but no code gets uploaded.

As a workaround, we have uploaded code using FTP client. But still need to find why the Jenkins build is breaking.

I am fairly new to Jenkins build process and I'd greatly appreciate any help/inputs! Thanks!!

### Relevant log output

```shell
- Uploading Zip
✖ Upload Failed
Error: Error: write EPROTO 140539191269184:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 40

    at Request._callback (/var/lib/jenkins/workspace/Staging Build v2/node_modules/sfcc-ci/lib/webdav.js:320:26)
    at self.callback (/var/lib/jenkins/workspace/Staging Build v2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:15)
    at Request.onRequestError (/var/lib/jenkins/workspace/Staging Build v2/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
- Cleaning Up Workspace
✔ Cleaning Up Workspace
```

**Comment by tobiaslohr** [comment]
@vruikar-desoto Can you provide the command that is failing and against which env (staging, development, sandbox)? Did you run with `--debug` mode to capture more verbose logging?

**Comment by vruikar-desoto** [comment]
Hello @tobiaslohr,
Apologies for not being able to respond earlier.
I believe  sfcc.webdav.upload() is breaking on staging instance.

**Comment by tobiaslohr** [comment]
Thanks @vruikar-desoto! Usually such errors are coming from the Node version being used. We've tested sfcc-ci using Node v14.16.x (LTS). Can you please try using this version?
