### ISSUE TITLE
Getting issue with deploy code with latest version

### ISSUE THREAD

**Issue by parvindersarora1** [SalesforceCommerceCloud/sfcc-ci#355]
### sfcc-ci Version

2.11.0

### NodeJS Version

14.17.6

### sfcc-ci Path

Bitbucket on linux

### Host OS Details

Not sure it is issue on bitbucket

### Description

Getting issue with sfcc-ci@latest version. Nothing change on pipeline or package only issue comes after latest version with sfcc-ci. Our last successful build was done 8 days earlier.  

### Relevant log output

```shell
npx sfcc-ci client:auth $API_KEY_VAR $APnI_SECRET_VAR 
10s
+ npx sfcc-ci client:auth $API_KEY_VAR $APnI_SECRET_VAR 
internal/modules/cjs/loader.js:905
  throw err;
  ^
Error: Cannot find module '/root/.npm/_npx/102/lib/node_modules/sfcc-ci/node_modules/snyk/dist/bootstrap.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snyk@1.1103.0 postinstall: `node dist/bootstrap.js exec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snyk@1.1103.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-14T19_47_24_569Z-debug.log
Install for [ 'sfcc-ci@latest' ] failed with code 1
```

**Comment by stm-dschulz** [comment]
Hi @parvindersarora1 ,

we experience the same issue. We tried the previous version https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/tag/v2.10.0 but have the same error. So assuming that this is somehow related to bitbucket pipelines.

We workarounded by using 
`npm install -g sfcc-ci`
`sfcc-ci client:auth`
instead of 
`npx sfcc-ci client:auth`

**Comment by dev-niko** [comment]
i am facing the same issue while installing sfcc-ci "npm install -g sfcc-ci" with image "node:lts-fermium"

**Comment by ricardoseifert** [comment]
Me too, 

npm install -g sfcc-ci wont run on my GitLab Pipeline. The image um using: image: node:lts-fermium. The Problem seems, that a sub dependency called "snyk" updated released a new version yesterday. 

The latest Version snyk@1.1103.0 seems causing my current problems: 

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/22746928/218987230-b7c9027f-2222-42a8-932c-2282337477c1.png">

**Comment by tobiaslohr** [comment]
Hi @parvindersarora1 @stm-dschulz @dev-niko @ricardoseifert , we've an open PR #470 which (hopefully) will fix this issue. Can you give that a try and provide feedback please?

**Comment by stm-dschulz** [comment]
Hi @tobiaslohr, 
the snyk change fixed the issue for us. Thx a lot!

**Comment by tobiaslohr** [comment]
Thanks @stm-dschulz!

@parvindersarora1 Can you please re-test on your side as well? PR #470 was merged into master, though no release has been built with that yet.
