### ISSUE TITLE
Uploading cartridges code to staging environment using the SFCC-CI client

### ISSUE THREAD

**Issue by gmoulin** [SalesforceCommerceCloud/sfcc-ci#474]
### sfcc-ci Version

2.11.0

### NodeJS Version

14.17.5

### sfcc-ci Path

/cygdrive/c/Users/g.moulin/AppData/Roaming/npm/sfcc-ci

### Host OS Details

Windows
Microsoft Windows 11 Pro
10.0.22000 N/A Build 22000

### Description

Hello,

I am currently using Eclipse and UX studio to upload code to a staging instance and I want to replace this setup with the SFCC-CI client.

I managed to install the tool using the documentation on https://github.com/SalesforceCommerceCloud/sfcc-ci .

I set up an account.demandware.com API key for it.
I set up my staging instance according to the documentation. ("Open Commerce API Settings" and "WebDAV Client Application Permissions")

I configured the dw.json file like this: (passwords and email redacted)
{
"client-id": "becf4f98-93d9-48fd-aa2f-d5d32953562b",
"client-secret": "xxxxxxxxxxxxxx",
"username": "g.moulin@xxxxx.com",
"password": "xxxxxxxxxxxxxx",
"hostname": "staging-eshop-xxxxx.demandware.net"
}

I manage to get the authentication and basic commands working.

But when I tried to upload code using the "sfcc-ci code:deploy" command, it does not work.

I tried:
- sfcc-ci code:deploy test.zip -i [www-staging.xxxxx.com](https://www-staging.xxxxx.com/)
Got a "403 Forbidden" error.

- sfcc-ci code:deploy test.zip -i [staging-eshop-xxxxx.demandware.net](https://staging-eshop-xxxxx.demandware.net/) -c /path/to/cert/cert.p12 -p "cert passphrase" -D
(redacted)
Got Error code: EPROTO, message: write EPROTO 19628:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40
, stack: Error: write EPROTO 19628:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40

- Checking the debug, I saw the "Assuming [staging-eshop-xxxxx.demandware.net](https://staging-eshop-xxxxx.demandware.net/) is a staging instance, replacing with cert.* format" sentence, so I tried
sfcc-ci code:deploy test.zip -i [cert.staging.eshop.xxxxx.demandware.net](https://cert.staging.eshop.xxxxx.demandware.net/) -c /path/to/cert/cert.p12 -p "cert passphrase" -D
Got the same error.

Please note that I can upload code using Eclipse and I have access to the staging environment WebDav using WinSCP without problems.

From my research, it seems the error is linked to the TLS version, but I did not find any solution to force it. (Already tried forcing the TLS version for node, without success)

### Relevant log output

```shell
[DEBUG] No dw.json found in C:\xxxxx\tmp
REQUEST {
  baseUrl: 'https://cert.staging.eshop.xxxxx.demandware.net',
  uri: '/on/demandware.servlet/webdav/Sites/cartridges/test.zip',
  auth: {
    bearer: 'eyJ0eXAiOiJKV1QiLCJraWQiOiJEMWhPUDdEODN4TjBqZWlqaTI3WWFvZFRjL0E9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJnLm1vdWxpbkB2aWxlYnJlcXVpbi5jb20iLCJjdHMiOiJPQVVUSDJfU1RBVEVMRVNTX0dSQU5UIiwiYXV0aF9sZXZlbCI6MCwiYXVkaXRUcmFja2luZ0lkIjoiYWJkZjZmZmUtM2E1Ny00YTQ3LWJiMGItZDBiMjVjNWY0NmRjLTU3MTI2NDQ4MCIsInN1Ym5hbWUiOiJnLm1vdWxpbkB2aWxlYnJlcXVpbi5jb20iLCJpc3MiOiJodHRwczovL2FjY291bnQuZGVtYW5kd2FyZS5jb206NDQzL2R3c3NvL29hdXRoMiIsInRva2VuTmFtZSI6ImFjY2Vzc190b2tlbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJhdXRoR3JhbnRJZCI6Ik9XUVQtTGxpZHp5VXBPTEZNVDhJaTdNbVBUTSIsImF1ZCI6ImJlY2Y0Zjk4LTkzZDktNDhmZC1hYTJmLWQ1ZDMyOTUzNTYyYiIsIm5iZiI6MTY3ODE4MTg4OSwiZ3JhbnRfdHlwZSI6InRva2VuIiwic2NvcGUiOlsidGVuYW50RmlsdGVyIiwicHJvZmlsZSIsInJvbGVzIl0sImF1dGhfdGltZSI6MTY3ODE4MTc0NCwicmVhbG0iOiIvIiwiZXhwIjoxNjc4MTgzNjg5LCJpYXQiOjE2NzgxODE4ODksImV4cGlyZXNfaW4iOjE4MDAsImp0aSI6ImNXanNJb2pzRU9YV2xNVjJocnp2c25ZNHAxcyIsImNsaWVudF9pZCI6ImJlY2Y0Zjk4LTkzZDktNDhmZC1hYTJmLWQ1ZDMyOTUzNTYyYiIsInRlbmFudEZpbHRlciI6IkNDRFhfU0JYX1VTRVI6YmJyZ19kZXYsYmJyZ19wcmQsYmJyZ19zMDEsYmJyZ19zMDIsYmJyZ19zMDMsYmJyZ19zMDQsYmJyZ19zMDUsYmJyZ19zMDYsYmJyZ19zYngsYmJyZ19zdGcsYmpma19kZXYsYmpma19wcmQsYmpma19zYngsYmpma19zdGc7Q1FVT1RJRU5UX0NPTkZJR1VSQVRPUl9BRE1JTjpiYnJnX2RldixiYnJnX3ByZCxiYnJnX3NieCxiYnJnX3N0ZyxiamZrX2RldixiamZrX3ByZCxiamZrX3NieCxiamZrX3N0ZztDUVVPVElFTlRfQ09ORklHVVJBVE9SX1VTRVI6YmJyZ19kZXYsYmJyZ19wcmQsYmJyZ19zYngsYmJyZ19zdGcsYmpma19kZXYsYmpma19wcmQsYmpma19zYngsYmpma19zdGc7Q1JNX09SR19BRE1JTjpiYnJnX2RldixiYnJnX3ByZCxiYnJnX3NieCxiYnJnX3N0ZyxiamZrX2RldixiamZrX3ByZCxiamZrX3NieCxiamZrX3N0ZztFQ09NX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfczAxLGJicmdfczAyLGJicmdfczAzLGJicmdfczA0LGJicmdfczA1LGJicmdfczA2LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO0xPR0NFTlRFUl9VU0VSOmJicmdfKixiYnJnX2RldixiYnJnX3ByZCxiYnJnX3NieCxiYnJnX3N0ZyxiamZrX2RldixiamZrX3ByZCxiamZrX3NieCxiamZrX3N0ZztPQ0FQSV9FWFBMT1JFUl9ERUJVR19VU0VSOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO09NX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO09NX1VTRVI6YmJyZ19kZXYsYmJyZ19wcmQsYmJyZ19zYngsYmJyZ19zdGcsYmpma19kZXYsYmpma19wcmQsYmpma19zYngsYmpma19zdGc7Uk5EX0NVU1RPTUVSX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO1JORF9QRVJGT1JNQU5DRV9VU0VSOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO1JORF9VU0VSOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO1NMQVNfT1JHQU5JWkFUSU9OX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnIiwicm9sZXMiOlsiRE9DX1VTRVIiLCJPTV9BRE1JTiIsIkFNX0FDQ09VTlRfQURNSU4iLCJDUVVPVElFTlRfQ09ORklHVVJBVE9SX0FETUlOIiwiU1RBVFVTX1BBR0VfSU9fVVNFUiIsIlhDSEFOR0VfVVNFUiIsIkFNX0FQSV9BRE1JTiIsIkVDT01fQURNSU4iLCJDUVVPVElFTlRfQ09ORklHVVJBVE9SX1VTRVIiLCJDQ19BRE1JTiIsIlJORF9VU0VSIiwiUk5EX0NVU1RPTUVSX0FETUlOIiwiQ0NfVVNFUiIsIkNSTV9PUkdfQURNSU4iLCJPQ0FQSV9FWFBMT1JFUl9ERUJVR19VU0VSIiwiU0xBU19PUkdBTklaQVRJT05fQURNSU4iLCJSTkRfUEVSRk9STUFOQ0VfVVNFUiIsIk9NX1VTRVIiLCJDQ0RYX1NCWF9VU0VSIiwiTE9HQ0VOVEVSX1VTRVIiXX0.ZU8H6ej66FI5w9Cap5TxyZ5dBxCL-_HG-3ipFnaZy90rm9Hw7wpzomDiQq-a-PFCcjfkX3zmP95l6l2y8Jp7bCCES-RNsskRPsiFNR0RqJUddeDKRr5_KB_zplFabqKcgraYlw46ljSPllYLi7TlY0bwWdnOzyp8WppBJYNwpFFnz8cgSXBfd_qtEcKQsSC-S4ZdYj5kMFpzn8N7mnAZbqRufuPlyE9RpYaekI21o-3m5-jZfJGCeMunV_Vs-SjxO0EbLqHngPjx8B2xd825mqjJNCoceuF8TeKBfRP1fj85myHBacT2-cB-eFUjuFkmHBNYXGtIgxU8ogvgF40RSQ'
  },
  strictSSL: true,
  method: 'PUT',
  callback: [Function (anonymous)]
}
REQUEST make request https://cert.staging.eshop.xxxxx.demandware.net/on/demandware.servlet/webdav/Sites/cartridges/test.zip
{
  request: {
    debugId: 1,
    uri: 'https://cert.staging.eshop.xxxxx.demandware.net/on/demandware.servlet/webdav/Sites/cartridges/test.zip',
    method: 'PUT',
    headers: {
      host: 'cert.staging.eshop.xxxxx.demandware.net',
      authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJraWQiOiJEMWhPUDdEODN4TjBqZWlqaTI3WWFvZFRjL0E9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJnLm1vdWxpbkB2aWxlYnJlcXVpbi5jb20iLCJjdHMiOiJPQVVUSDJfU1RBVEVMRVNTX0dSQU5UIiwiYXV0aF9sZXZlbCI6MCwiYXVkaXRUcmFja2luZ0lkIjoiYWJkZjZmZmUtM2E1Ny00YTQ3LWJiMGItZDBiMjVjNWY0NmRjLTU3MTI2NDQ4MCIsInN1Ym5hbWUiOiJnLm1vdWxpbkB2aWxlYnJlcXVpbi5jb20iLCJpc3MiOiJodHRwczovL2FjY291bnQuZGVtYW5kd2FyZS5jb206NDQzL2R3c3NvL29hdXRoMiIsInRva2VuTmFtZSI6ImFjY2Vzc190b2tlbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJhdXRoR3JhbnRJZCI6Ik9XUVQtTGxpZHp5VXBPTEZNVDhJaTdNbVBUTSIsImF1ZCI6ImJlY2Y0Zjk4LTkzZDktNDhmZC1hYTJmLWQ1ZDMyOTUzNTYyYiIsIm5iZiI6MTY3ODE4MTg4OSwiZ3JhbnRfdHlwZSI6InRva2VuIiwic2NvcGUiOlsidGVuYW50RmlsdGVyIiwicHJvZmlsZSIsInJvbGVzIl0sImF1dGhfdGltZSI6MTY3ODE4MTc0NCwicmVhbG0iOiIvIiwiZXhwIjoxNjc4MTgzNjg5LCJpYXQiOjE2NzgxODE4ODksImV4cGlyZXNfaW4iOjE4MDAsImp0aSI6ImNXanNJb2pzRU9YV2xNVjJocnp2c25ZNHAxcyIsImNsaWVudF9pZCI6ImJlY2Y0Zjk4LTkzZDktNDhmZC1hYTJmLWQ1ZDMyOTUzNTYyYiIsInRlbmFudEZpbHRlciI6IkNDRFhfU0JYX1VTRVI6YmJyZ19kZXYsYmJyZ19wcmQsYmJyZ19zMDEsYmJyZ19zMDIsYmJyZ19zMDMsYmJyZ19zMDQsYmJyZ19zMDUsYmJyZ19zMDYsYmJyZ19zYngsYmJyZ19zdGcsYmpma19kZXYsYmpma19wcmQsYmpma19zYngsYmpma19zdGc7Q1FVT1RJRU5UX0NPTkZJR1VSQVRPUl9BRE1JTjpiYnJnX2RldixiYnJnX3ByZCxiYnJnX3NieCxiYnJnX3N0ZyxiamZrX2RldixiamZrX3ByZCxiamZrX3NieCxiamZrX3N0ZztDUVVPVElFTlRfQ09ORklHVVJBVE9SX1VTRVI6YmJyZ19kZXYsYmJyZ19wcmQsYmJyZ19zYngsYmJyZ19zdGcsYmpma19kZXYsYmpma19wcmQsYmpma19zYngsYmpma19zdGc7Q1JNX09SR19BRE1JTjpiYnJnX2RldixiYnJnX3ByZCxiYnJnX3NieCxiYnJnX3N0ZyxiamZrX2RldixiamZrX3ByZCxiamZrX3NieCxiamZrX3N0ZztFQ09NX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfczAxLGJicmdfczAyLGJicmdfczAzLGJicmdfczA0LGJicmdfczA1LGJicmdfczA2LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO0xPR0NFTlRFUl9VU0VSOmJicmdfKixiYnJnX2RldixiYnJnX3ByZCxiYnJnX3NieCxiYnJnX3N0ZyxiamZrX2RldixiamZrX3ByZCxiamZrX3NieCxiamZrX3N0ZztPQ0FQSV9FWFBMT1JFUl9ERUJVR19VU0VSOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO09NX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO09NX1VTRVI6YmJyZ19kZXYsYmJyZ19wcmQsYmJyZ19zYngsYmJyZ19zdGcsYmpma19kZXYsYmpma19wcmQsYmpma19zYngsYmpma19zdGc7Uk5EX0NVU1RPTUVSX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO1JORF9QRVJGT1JNQU5DRV9VU0VSOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO1JORF9VU0VSOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnO1NMQVNfT1JHQU5JWkFUSU9OX0FETUlOOmJicmdfZGV2LGJicmdfcHJkLGJicmdfc2J4LGJicmdfc3RnLGJqZmtfZGV2LGJqZmtfcHJkLGJqZmtfc2J4LGJqZmtfc3RnIiwicm9sZXMiOlsiRE9DX1VTRVIiLCJPTV9BRE1JTiIsIkFNX0FDQ09VTlRfQURNSU4iLCJDUVVPVElFTlRfQ09ORklHVVJBVE9SX0FETUlOIiwiU1RBVFVTX1BBR0VfSU9fVVNFUiIsIlhDSEFOR0VfVVNFUiIsIkFNX0FQSV9BRE1JTiIsIkVDT01fQURNSU4iLCJDUVVPVElFTlRfQ09ORklHVVJBVE9SX1VTRVIiLCJDQ19BRE1JTiIsIlJORF9VU0VSIiwiUk5EX0NVU1RPTUVSX0FETUlOIiwiQ0NfVVNFUiIsIkNSTV9PUkdfQURNSU4iLCJPQ0FQSV9FWFBMT1JFUl9ERUJVR19VU0VSIiwiU0xBU19PUkdBTklaQVRJT05fQURNSU4iLCJSTkRfUEVSRk9STUFOQ0VfVVNFUiIsIk9NX1VTRVIiLCJDQ0RYX1NCWF9VU0VSIiwiTE9HQ0VOVEVSX1VTRVIiXX0.ZU8H6ej66FI5w9Cap5TxyZ5dBxCL-_HG-3ipFnaZy90rm9Hw7wpzomDiQq-a-PFCcjfkX3zmP95l6l2y8Jp7bCCES-RNsskRPsiFNR0RqJUddeDKRr5_KB_zplFabqKcgraYlw46ljSPllYLi7TlY0bwWdnOzyp8WppBJYNwpFFnz8cgSXBfd_qtEcKQsSC-S4ZdYj5kMFpzn8N7mnAZbqRufuPlyE9RpYaekI21o-3m5-jZfJGCeMunV_Vs-SjxO0EbLqHngPjx8B2xd825mqjJNCoceuF8TeKBfRP1fj85myHBacT2-cB-eFUjuFkmHBNYXGtIgxU8ogvgF40RSQ',
      'content-type': 'application/zip'
    }
  }
}
Error: Network or certificate error
Error: An error occured. Try running the command again with -D,--debug flag.
[DEBUG] Error code: EPROTO, message: write EPROTO 11680:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40
, stack: Error: write EPROTO 11680:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
```

**Comment by esmiralha** [comment]
any news on that bug? We have tried with node v14.16.1 and have regenerated the certificate without success.

**Comment by jelizaldecapptus** [comment]
I have subscribed to this issue because I am experiencing the exact same behavior, with the one difference that I was able to deploy the code the first time without any troubles, but trying it a second time has given me the errors @gmoulin mentioned. I have tried the same steps mentioned in the bug and still receiving the same error.

```
Error: Network or certificate error
Error: An error occured. Try running the command again with -D,--debug flag.
[DEBUG] Error code: EPROTO, message: write EPROTO 4456170880:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1563:SSL alert number 40
, stack: Error: write EPROTO 4456170880:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1563:SSL alert number 40

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
```

**Comment by rohanmallick08** [comment]
Did anyone figured out the issue and any solutions to fix it?

**Comment by christopherjanzen** [comment]
It seems we are facing the same issue here. Following for potential fix.

**Comment by sneha-ranosys** [comment]
Facing the same issue with error :
Error code: undefined, message: mac verify failure, stack: Error: mac verify failure
Did anyone figureed out the issue and any solutions to fix it?
