### ISSUE TITLE
Local issuer certificate error with sfcc-ci npm install 

### ISSUE THREAD

**Issue by rpillamerkle** [SalesforceCommerceCloud/sfcc-ci#500]
### sfcc-ci Version

2.11

### NodeJS Version

10.23

### What happened?

We are trying to do npm install where we have sfcc-ci as a dependency in the package.json
"sfcc-ci": "SalesforceCommerceCloud/sfcc-ci#v2.11.0"

npm is throwing an error while installing sfcc-ci dependency. It is failing at prepare: npm run synk-protect. We have tried with the later versions of node, but no luck.

At the end it should NOPACKAGEJSON error even through repo contains the package.json

<img width="647" alt="image" src="https://github.com/SalesforceCommerceCloud/sfcc-ci/assets/105309413/f9587a34-a45f-42a1-9a07-e8daa067de30">

Anyone faced this issue?

**Comment by tobiaslohr** [comment]
Hi @rpillamerkle, in the screenshot it says version v2.6.0, whereas in the description you say v2.11.0. Can you clarify please?

In current master (precisely in commit https://github.com/SalesforceCommerceCloud/sfcc-ci/commit/d6e64578f4cceeab7f8c8285ccd5a5307d75e6c6) there is a change related to snyk protect. Just to verify: can you depend from that and see if the npm install is working fine then?

**Comment by rpillamerkle** [comment]
@tobiaslohr Thanks for the reply. I was just trying different versions. So, the same error shows up for both the versions. We have used the commit version that you mentioned, the error shows up for that version as well.

**Comment by TimothyMBaB** [comment]
The versions are a bit confused because this is being asked on behalf of multiple people with some differences of versions. I was the first, and I have ci 2.11 and node 12.22.12, while another has ci 2.6 and node 10.23. The errors are identical, however.

I've also tried installing 2.11 globally and using "sfcc-ci client:auth" It gives basically the same error with a slightly different trace:
Error: Authentication failed: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
